services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insighthub-app
    working_dir: /var/www/html
    #command: >
    #  sh -c "
    #    php artisan config:cache &&
    #    php artisan route:cache &&
    #    php artisan view:cache &&
    #    composer dump-autoload --optimize &&
    #    php artisan migrate --force &&
    #    php artisan serve --host=0.0.0.0 --port=8000
    #  "
    #environment:
     # - APP_ENV=production
     # - DB_HOST=host.docker.internal
     # - DB_DATABASE=resrepo
     # - DB_USERNAME=root
     # - DB_PASSWORD=140053ken!
    #depends_on:
      # - db  # Removed since db service is not used

  vite:
    image: node:20-alpine
    container_name: insighthub-vite
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    # No ports exposed, just builds assets

  nginx:
    image: nginx:alpine
    container_name: insighthub-nginx
    ports:
      - "8001:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

# db service removed
# volumes section removed since only used by db
