
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insighthub-app
    working_dir: /var/www/html
    volumes:
      - storage-data:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - public-assets:/shared/public
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - APP_ENV=production
      - APP_URL=http://localhost:8001
      - APP_DEBUG=false
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: insighthub-nginx
    ports:
      - "8001:80"
    volumes:
      - public-assets:/var/www/html/public:ro
      - storage-data:/var/www/html/storage:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  public-assets:
  storage-data:

networks:
  app-network:
    driver: bridge
